In [1]:
#Numpy Basic Assignment
"""Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables."""

Ans:  Yes, there is a difference in the data type of variables list_ and array_list.

print(type(list_))
#Output: 
<class 'list'>

print(type(array_list))
#output
<class 'numpy.ndarray'>

"""Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list."""
Ans: 
list_ = [1, 2.5, 'Hello', True]
array_list = np.array([1, 2.5, 'Hello', True])

for element in list_:
    print(type(element))
    
for element in array_list:
    print(type(element))
    
# Output
<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.str_'>
<class 'numpy.bool_'>

"""Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then 
print the data types of each and every element present in both the variables, list_ and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)"""

Ans: Yes, there will be a difference in the data type of the elements present in both the variables, list_ and array_list. 
The data type of each and every element present in list_ will be of type 'object' while the data type of each and every element
present in array_list will be of type 'int'. 
For example, in the above code, the data type of each and every element present in num_list will be of type 'object' while the
data type of each and every element present in num_array will be of type 'int'.

"""Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size"""

Ans:
import numpy as np 
num_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
  
# (i) shape 
print("Shape of array:", num_array.shape) 
  
# (ii) size 
print("Size of array:", num_array.size) 

#output
Shape of array: (3, 3)
Size of array: 9


"""import numpy as np

arr = np.zeros((3,3))
print(arr)"""

Ans: 
import numpy as np

arr = np.zeros((3,3))
print(arr)

#output
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

"""Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]"""

Ans: 
import numpy as np
np.identity(5)

#Output
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])
